fixed commits
diging/place_name_resolver pull request #1
Opened 2020-12-18 18:23 UTC by tjquinn1

2020-12-18 18:26 UTC, tjquinn1 commented
I didn't end up using poetry because I was having a bunch of issues. I think it is a local issue but didn't want to spend any more time on it.

2021-01-12 20:02 UTC, jdamerow requested changes

2021-01-12 20:02 UTC, jdamerow commented on place_resolver.py
> +    def process_length_2_coords(coords):
where is this being used? should that be used in lines 112 and 123?

2021-01-12 20:02 UTC, jdamerow commented on place_resolver.py
> +            if string in ["N", "E"]:
I take it that N, E, S, W are at the end of a coordinate string? an example in a comment/documentation would help to understand what this is doing.

2021-01-25 21:05 UTC, jdamerow commented
I get this exception:
```
Traceback (most recent call last):
  File "place_resolver.py", line 245, in <module>
    main()
  File "place_resolver.py", line 237, in main
    result = resolver.resolve_place(place["place_name"])
  File "place_resolver.py", line 152, in resolve_place
    'cleaned_coordinates': self.clean_coordinates(potential_place_entries[0]['coordinates'])
TypeError: clean_coordinates() takes 1 positional argument but 2 were given
```

2021-03-18 16:52 UTC, jdamerow commented
closing due to coordinate bug

2021-03-19 13:53 UTC, merged